# GoReleaser configuration for redirect-server
# Documentation: https://goreleaser.com

version: 2

project_name: redirect-server

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  - id: redirect-server
    main: ./redirect-server
    binary: redirect-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      # macOS doesn't support 32-bit or ARM v6/7
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      # Windows ARM is rare
      - goos: windows
        goarch: arm
      # FreeBSD ARM builds (optional, can enable if needed)
      - goos: freebsd
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds:
      - redirect-server
    rlcp: true
    files:
      - README.md
      - LICENSE*
      - config.example.json
      - mapping.example.json
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'typo'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: PasarGuard
    name: migrations
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Redirect Server Release {{ .Tag }}

    This release contains pre-built binaries for multiple platforms and architectures.

    ### Installation

    Download the appropriate binary for your system from the assets below.

    **Example for Linux amd64:**
    ```bash
    wget https://github.com/PasarGuard/migrations/releases/download/{{ .Tag }}/redirect-server_{{ .Version }}_Linux_x86_64.tar.gz
    tar -xzf redirect-server_{{ .Version }}_Linux_x86_64.tar.gz
    chmod +x redirect-server
    ./redirect-server --help
    ```
  footer: |
    **Full Changelog**: https://github.com/PasarGuard/migrations/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    **Verify checksums**: Download `checksums.txt` and verify with `sha256sum -c checksums.txt`

# Optional: Generate Software Bill of Materials
# sboms:
#   - artifacts: archive

# Optional: Sign binaries (requires signing keys)
# signs:
#   - cmd: cosign
#     artifacts: checksum
#     args:
#       - sign-blob
#       - --output-signature=${signature}
#       - ${artifact}
